### ISSUE TITLE
1.19.2 Told It Works In 1.19.4, But Instead I Get This Error

### ISSUE THREAD

**Issue by TheWrongCrafter** [vectorwing/FarmersDelight#848]
-- Head --
Thread: Render thread
Stacktrace:
	at vectorwing.farmersdelight.FarmersDelight$1.<init>(FarmersDelight.java:34) ~[FarmersDelight-1.19.2-1.2.3.jar%23190!/:1.19.2-1.2.3] {re:classloading}
-- MOD farmersdelight --
Details:
	Mod File: /C:/Users/RecaTWC/curseforge/minecraft/Modpack 1/Instances/The Rotting Dead (1)/mods/FarmersDelight-1.19.2-1.2.3.jar
	Failure message: Farmer's Delight (farmersdelight) has failed to load correctly
		java.lang.NoSuchMethodError: 'void net.minecraft.world.item.CreativeModeTab.<init>(java.lang.String)'
	Mod Version: 1.19.2-1.2.3
	Exception message: java.lang.NoSuchMethodError: 'void net.minecraft.world.item.CreativeModeTab.<init>(java.lang.String)'
Stacktrace:
	at vectorwing.farmersdelight.FarmersDelight$1.<init>(FarmersDelight.java:34) ~[FarmersDelight-1.19.2-1.2.3.jar%23190!/:1.19.2-1.2.3] {re:classloading}
	at vectorwing.farmersdelight.FarmersDelight.<clinit>(FarmersDelight.java:33) ~[FarmersDelight-1.19.2-1.2.3.jar%23190!/:1.19.2-1.2.3] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.4-45.2.0.jar%23206!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.4-45.2.0.jar%23205!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

The Full File:

[crash-2023-12-07_03.40.47-fml.txt](https://github.com/vectorwing/FarmersDelight/files/13599627/crash-2023-12-07_03.40.47-fml.txt)

**Comment by vectorwing** [comment]
1.19.2 and 1.19.4 mod releases are generally incompatible, due to several breaking changes in vanilla code.
FD has only been ported to 1.19.2, therefore it can't be run on 1.19.4. I don't currently have plants to port it to .4, as it's not widely adopted by other mods.
